# cloudbuild.yaml for Google Cloud Build (Python unit tests)

steps:
  - name: 'us-west1-docker.pkg.dev/vertex-debugging/cloud-build-spike/python-builder:0.1'
    entrypoint: 'go-test'
    args: ['tests'] 
  - name: 'python'
    entrypoint: 'python'
    args: ['-m', 'pip', 'freeze'] 
  - name: 'python'
    entrypoint: 'python'
    args: ['-m', 'pytest', 'tests/'] 
logsBucket: 'gs://my-cloud-loggy-logger'