# cloudbuild.yaml for Google Cloud Build (Python unit tests)

steps:
  - name: 'python'
    entrypoint: 'python'
    args: ['-m', 'pip', 'install', '.[dev]', '--user'] 
  - name: 'python'
    entrypoint: 'python'
    args: ['-m', 'pip', 'freeze'] 
  - name: 'python'
    entrypoint: 'python'
    args: ['-m', 'pytest', 'tests/'] 

options:
  logging: CLOUD_LOGGING_ONLY